name: crm
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin036203
      MONGO_INITDB_DATABASE: crm_main
    volumes:
      - ./db/:/data/db
    networks:
      - crm_network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    environment:
      - PORT=3000
      # - MONGODB_URL=mongodb://admin:admin036203@mongodb-container:27017/crm_main?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - "mongodb"
    volumes:
       - ./server:/usr/src/server
       - /usr/src/server/node_modules
    networks:
      - crm_network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - "mongodb"
    volumes:
       - ./client:/usr/src/client
       - /usr/src/client/node_modules
    networks:
      - crm_network
networks:
  crm_network:
    driver: bridge